### ISSUE TITLE
Support looping the entire playlist

### ISSUE THREAD

**Issue by xiaogaozi** [victoralvesf/aonsoku#60]
First of all thanks a lot for contributing this awesome music player!

My request is that I would like to be able to loop the entire playlist, as right now I can only loop a single song.

**Comment by victoralvesf** [comment]
Thank you so much for your feedback and for using the app!

The initial features were designed to deliver core functionality as quickly as possible, which is why the current loop option only applies to single songs. Expanding this to include playlist looping is indeed on the roadmap for future updates.

Thank you for your support as we continue improving the player!
